spring:
  liquibase:
    change-log: classpath:db/liquibase-master.xml

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database: H2
    show-sql: false
    open-in-view: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:vaccineNotifier
    #    url: jdbc:h2:tcp://localhost/~/scheduleServices;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: plato-dev
    password:
    properties:
      javax.persistence.query.timeout: 3000
      hibernate.connection.release_mode: AFTER_TRANSACTION

liquibase:
  contexts: dev


server:
  port: 8085

application:
  url:
    cdn:
      covinByDistrict: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict
      states: https://cdn-api.co-vin.in/api/v2/admin/location/states
      districts: https://cdn-api.co-vin.in/api/v2/admin/location/districts/
      calenderByDistrict: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict
  userName: anonymous.mhais@gmail.com
  password: Chats@6585
